class MapValidator
  def getVocabularies
    {
      dateQualifierVocabularies: [
        '[blank]',
        'Approximate'
      ],
      format: [
        'File/document - Paper',
        'File/document - Parchment',
        'File/document - Other',
        'Cards - Paper/card',
        'Cards - Punchcard',
        'Cards - Other',
        'Volume/register - Register - leather bound',
        'Volume/register - Register - non leather bound',
        'Volume/register - Spiral bound',
        'Volume/register - Post bound',
        'Volume/register - Ring bound',
        'Volume/register - Perfect bound',
        'Volume/register - Album',
        'Volume/register - Notebook',
        'Volume/register - Copy Press (letterpress)',
        'Volume/register - Copy Press (iron gall ink)',
        'Volume/register - Parchment',
        'Volume/register - Other',
        'Chart (produced by machine) - Machine-generated (eg seismic, gyro)',
        'Chart (produced by machine) - Stenotype Tape/Paper',
        'Chart (produced by machine) - Other',
        'Map/plan - Film',
        'Map/plan - Paper',
        'Map/plan - Linen',
        'Map/plan - Composite',
        'Map/plan - Blueprint - negative',
        'Map/plan - Blueprint - positive',
        'Map/plan - Other',
        'Architectural or technical drawing - Film',
        'Architectural or technical drawing - Paper',
        'Architectural or technical drawing - Linen',
        'Architectural or technical drawing - Composite',
        'Architectural or technical drawing - Blueprint - negative',
        'Architectural or technical drawing - Blueprint - positive',
        'Architectural or technical drawing - Other',
        'Artwork - Poster - framed',
        'Artwork - Poster - unframed',
        'Artwork - Painting - unframed',
        'Artwork - Painting - framed',
        'Artwork - Print - framed',
        'Artwork - Print - unframed',
        'Artwork - Sketch - framed',
        'Artwork - Sketch - unframed',
        'Artwork - Banner',
        'Artwork - Other',
        'Microform - Microfilm 35mm Master',
        'Microform - Microfilm 16mm Master',
        'Microform - Microfilm 35mm Duplicate',
        'Microform - Microfilm 16mm Duplicate',
        'Microform - Microfilm 35mm Security',
        'Microform - Microfilm 16mm Security',
        'Microform - Microfiche',
        'Microform - Aperture card',
        'Microform - Other',
        'Tape - sound recording  - Audio 1/4" reel',
        'Tape - sound recording  - Audio 1" reel',
        'Tape - sound recording  - Audio 2" reel',
        'Tape - sound recording  - Compact casette',
        'Tape - sound recording  - Micro cassette',
        'Tape - sound recording  - Mini cassette',
        'Tape - sound recording  - 8 Track audio',
        'Tape - sound recording  - Other',
        'Film (roll) - Motion picture - 35mm - acetate',
        'Film (roll) - Motion picture - 35mm - polyester',
        'Film (roll) - Motion picture - 16mm - acetate',
        'Film (roll) - Motion picture - 16mm - polyester',
        'Film (roll) - Motion picture - 8mm acetate',
        'Film (roll) - Motion picture - 8mm - polyester',
        'Film (roll) - Motion picture - Super 8 - acetate',
        'Film (roll) - Motion picture - Super 8 - poylester',
        'Film (roll) - Aerial film roll - acetate',
        'Film (roll) - Aerial film roll - polyester',
        'Film (roll) - Other',
        'Film (video) - VHS',
        'Film (video) - Super VHS',
        'Film (video) - U-Matic 3/4"',
        'Film (video) - U-Matic small',
        'Film (video) - Video casette other (handicam)',
        'Film (video) - Betamax',
        'Film (video) - Betacam',
        'Film (video) - 1" tape',
        'Film (video) - 2" tape',
        'Film (video) - Other',
        'Photographic  - Print - B&W',
        'Photographic  - Print - Colour',
        'Photographic  - Print - framed',
        'Photographic  - Negative - 35mm - B&W - undetermined',
        'Photographic  - Negative - 35mm - B&W - acetate',
        'Photographic  - Negative - 35mm - B&W - polyester',
        'Photographic  - Negative - 35mm - Colour - undetermined',
        'Photographic  - Negative - 35mm - Colour - acetate',
        'Photographic  - Negative - 35mm - Colour - polyester',
        'Photographic  - Negative - 120 - B&W - polyester',
        'Photographic  - Negative - 120 - B&W - acetate',
        'Photographic  - Negative - 120 - B&W - undetermined',
        'Photographic  - Negative - 120 - Colour - acetate',
        'Photographic  - Negative - 120 - Colour - polyester',
        'Photographic  - Negative - 120 - Colour - undetermined',
        'Photographic  - Negative - 4 x 5 - B&W - acetate',
        'Photographic  - Negative - 4 x 5 - B&W - polyester',
        'Photographic  - Negative - 4 x 5 - B&W - undetermined',
        'Photographic  - Negative - 8 x 10 - B&W - acetate',
        'Photographic  - Negative - 8 x 10 - B&W - polyester',
        'Photographic  - Negative - 8 x 10 - B&W - undetermined',
        'Photographic  - Transparency 35mm - colour - acetate',
        'Photographic  - Transparency 35mm - colour - polyester',
        'Photographic  - Transparency 35mm - colour - undetermined',
        'Photographic  - Transparency 120 - colour - acetate',
        'Photographic  - Transparency 120 - colour - polyester',
        'Photographic  - Transparency 120 - colour - undetermined',
        'Photographic  - Transparency 4 x 5 - colour',
        'Photographic  - Glass Plate Negative - full plate',
        'Photographic  - Glass Plate Negative - half plate',
        'Photographic  - Glass Plate Negative - quarter plate',
        'Photographic  - Glass Plate Negative - lantern slide',
        'Photographic  - Glass Plate Negative - mammoth',
        'Photographic  - Slide - 35mm - B&W - undetermined',
        'Photographic  - Slide - 35mm - B&W - acetate',
        'Photographic  - Slide - 35mm - B&W - polyester',
        'Photographic  - Slide - 120 - B&W - undetermined',
        'Photographic  - Slide - 120 - B&W - acetate',
        'Photographic  - Slide - 120 - B&W - polyester',
        'Photographic  - Slide - 35mm - Colour - undetermined',
        'Photographic  - Slide - 35mm - Colour - acetate',
        'Photographic  - Slide - 35mm - Colour - polyester',
        'Photographic  - Slide - 120 - Colour - undetermined',
        'Photographic  - Slide - 120 - Colour - acetate',
        'Photographic  - Slide - 120 - Colour - polyester',
        'Photographic  - Other',
        'Digital media - Flashdrive/USB/Thumbdrive',
        'Digital media - External hard drive',
        'Digital media - Internal hard drive',
        'Digital media - Network Attached Storage (NAS)',
        'Digital media - PC',
        'Digital media - Server',
        'Digital media - Optical CD',
        'Digital media - Optical DVD',
        'Digital media - LTO computer tape',
        'Digital media - Floppy disc - 8"',
        'Digital media - Floppy disc - 3 1/2"',
        'Digital media - Floppy disc - 5 1/4"',
        'Digital media - Other',
        'Object - Equipment',
        'Object - Architectural model/marquette',
        'Object - Medals',
        'Object - Currency',
        'Object - Honour Board',
        'Object - Printing Blocks',
        'Object - Specimens',
        'Object - Other',
        'Other'
      ],
      containedWithin: [
        'Aerial film canister',
        'Album',
        'Bundle',
        'Card box',
        'Card Drawer',
        'Encapsulate',
        'Film canister - non-vented',
        'Film canister - vented',
        'Folder',
        'Map folder',
        'Microfiche box',
        'Microfilm box',
        'No container',
        'Other',
        'Phase Box',
        'Slide carousel',
        'Solander Box',
        'Type 1 box',
        'Type 10 box',
        'Type 11 box',
        'Type 2 box',
        'Type 3.1 box',
        'Type 5.1 box',
        'Type 6 box',
        'Box - other',
        'Wrapping'
    ],
      accessCategories: [
        '0',
        '5',
        '10',
        '15',
        '20',
        '25',
        '30',
        '35',
        '40',
        '45',
        '50',
        '55',
        '60',
        '65',
        '70',
        '75',
        '80',
        '85',
        '90',
        '95',
        '100',
        'Overriding Legislation',
        'Non Publication Order',
        'Sealed By Court'
      ],
      sensitivityLabels: [
        'Cultural Sensitivity Warning',
        'Public Access/Published',
        'Secret and Sacred',
        'These records may contain terms or images which Aboriginal and Torres Strait Islander people may find distressing or offensive',
        'This record may contain information or photographs which some people may find distressing'
      ],
      representationType: [
        'Digital',
        'Physical'
      ]
    }
  end
end
